name: Tests

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
        - labeled
        - unlabeled
    push:

jobs:
  go_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make test
